repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports',
               '--exclude=tests/conftest.py']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://gitlab.com/retnikt/flake9
    rev: 3.8.3.post1
    hooks:
      - id: flake8
        files: ^functimer/
        additional_dependencies: [flake8-bugbear, flake8-print, flake8-pylint]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-toml
      - id: check-added-large-files
