language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install poetry
  - pip install tox-travis
  - pip install codecov
install:
  - poetry install
script:
  - poetry run pre-commit run --all-files
  - poetry run tox
after_success:
  - codecov
